apiVersion: v1
kind: Pod
metadata:
  name: test-scc-pod
spec:
  serviceAccountName: test-scc-sa
  securityContext:
    runAsUser: 0
  containers:
    - name: pause
      image: gcr.io/google_containers/pause
      resources:
        limits:
          cpu: "100"
          memory: "100Gi"
