apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-scc-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resourceNames:
  - test-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
