apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-scc-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-scc-role
subjects:
  - kind: ServiceAccount
    name: test-scc-sa
