pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=mover-rsync/Build
      - check-success=Lint
    actions:
      merge:
        method: merge
