---
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - check-success=Lint-mover-rsync
      - check-success=Build-mover-rsync
      - check-success=Lint
      - check-success=Build-operator
    actions:
      merge:
        method: squash
