apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "scribe.backube/v1alpha1",
          "kind": "ReplicationDestination",
          "metadata": {
            "name": "replicationdestination-sample"
          },
          "spec": {
            "rsync": {
              "accessModes": [
                "ReadWriteOnce"
              ],
              "capacity": "10Gi",
              "copyMethod": "Snapshot",
              "serviceType": "ClusterIP"
            }
          }
        },
        {
          "apiVersion": "scribe.backube/v1alpha1",
          "kind": "ReplicationSource",
          "metadata": {
            "name": "replicationsource-sample"
          },
          "spec": {
            "rsync": {
              "address": "my.host.com",
              "copyMethod": "Clone",
              "sshKeys": "secretRef"
            },
            "sourcePVC": "pvcname",
            "trigger": {
              "schedule": "0 * * * *"
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.4.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: scribe.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ReplicationDestination defines the destination for a replicated volume
      displayName: Replication Destination
      kind: ReplicationDestination
      name: replicationdestinations.scribe.backube
      version: v1alpha1
    - description: ReplicationSource defines the source for a replicated volume
      displayName: Replication Source
      kind: ReplicationSource
      name: replicationsources.scribe.backube
      version: v1alpha1
  description: Scribe asynchronously replicates Kubernetes persistent volumes between clusters using either rsync or rclone depending on the number of destinations.
  displayName: scribe-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - batch
          resources:
          - jobs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - scribe.backube
          resources:
          - replicationdestinations
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - scribe.backube
          resources:
          - replicationdestinations/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - scribe.backube
          resources:
          - replicationdestinations/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - scribe.backube
          resources:
          - replicationsources
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - scribe.backube
          resources:
          - replicationsources/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - scribe.backube
          resources:
          - replicationsources/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - scribe-mover
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - snapshot.storage.k8s.io
          resources:
          - volumesnapshots
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: scribe-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                image: quay.io/backube/scribe:latest
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 300Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - data replication
  links:
  - name: Scribe
    url: https://scribe.domain
  maturity: alpha
  provider:
    name: backube
    url: https://github.com/backube/scribe
  version: 0.1.0
