# permissions for end users to edit destinations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: destination-editor-role
rules:
- apiGroups:
  - scribe.backube
  resources:
  - destinations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scribe.backube
  resources:
  - destinations/status
  verbs:
  - get
