apiVersion: scribe.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: replicationdestination-sample
spec:
  rsync:
    serviceType: LoadBalancer
    copyMethod: Snapshot
    capacity: 10Gi
    accessModes: [ReadWriteOnce]

