---
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default
ignore: |
  config/**
  hack/crds/*
  helm/scribe/**
rules:
  indentation:
    indent-sequences: consistent
  line-length:
    allow-non-breakable-inline-mappings: true
    ignore: |
      test-kuttl/**
